---
title: "p8105_hw5_sm5134"
author: "Sneha Mehta"
date: "2022-11-15"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE)
```

## Problem 1
```{r}
dataframe = 
  tibble(
    files = list.files("./hw5_data/data/"),
    path = str_c("./hw5_data/data/", files)
  ) %>% 
  mutate(data = map(path, read_csv))  %>% 
  unnest()
```

Tidying dataframe
```{r}
dataframe_tidy = 
  dataframe %>% 
  mutate(
    files = str_replace(files, ".csv", ""),
    group = str_sub(files, 1, 3)) %>% 
  pivot_longer(
    week_1:week_8,
    names_to = "week",
    values_to = "outcome",
    names_prefix = "week_") %>% 
  mutate(week = as.numeric(week)) %>% 
  select(group, subj = files, week, outcome)
```

Creating spaghetti plot
```{r}
dataframe_tidy %>% 
  ggplot(aes(x = week, y = outcome, group = subj, color = group)) + 
  geom_point() + 
  geom_path() + 
  facet_grid(~group)
```
From the plot we can see that over the course of the study, the outcome measure for the control group was relatively stagnant. However, the outcome measure increased over time for the experimental group.

## Problem 2
```{r}
homicide = read_csv("./hw5_data/homicide-data.csv") %>% 
  janitor::clean_names() %>% 
  mutate(city_state = str_c(city, state, sep = ", "))

homicide_summ = homicide %>% 
  group_by(city_state) %>% 
  summarise(homicide_total = n(), 
            unsolved = sum(!(disposition == "Closed by arrest"))) %>% 
  prop.test(unsolved, )
```

